# Generated by Django 4.1.5 on 2023-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_episode', models.CharField(help_text='S00E00', max_length=15, verbose_name='Season/Episode')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateField(verbose_name='Date Added')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
        ),
    ]
