# Generated by Django 4.1.5 on 2023-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickAway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='des', max_length=500),
        ),
    ]
