# Generated by Django 4.1.5 on 2023-02-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickAway', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
