# Generated by Django 4.1.5 on 2023-02-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickAway', '0005_alter_post_description_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date Added'),
        ),
    ]
