# Generated by Django 4.1.5 on 2023-02-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickAway', '0008_alter_post_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
