# Generated by Django 4.2a1 on 2023-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickAway', '0009_alter_post_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
