# Generated by Django 4.1.4 on 2023-01-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_naame',
            new_name='user_Name',
        ),
    ]
