# Generated by Django 4.1.4 on 2023-01-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_rename_user_naame_person_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
