# Generated by Django 4.1.4 on 2023-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseApp', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('User_Name', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
